//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Decker.rc
//
#define IDD_INTRO                       102
#define IDC_HOME_CHAR                   101
#define IDC_HOME_CONTRACT               102
#define IDC_HOME_BUY                    103
#define IDC_HOME_PROGRAM                104
#define IDC_HOME_REST                   105
#define IDC_HOME_DECK                   106
#define IDC_HOME_MATRIX                 107
#define IDC_OPTIONS                     108
#define IDC_MATRIX_N                    111
#define IDC_MATRIX_S                    112
#define IDC_MATRIX_E                    113
#define IDC_MATRIX_W                    114
#define IDC_MATRIX_DISCONNECT           115
#define IDC_MAP_ZOOM                    116
#define IDC_SOFTWARE_LIST               117
#define IDC_RUN_PROGRAM                 118
#define IDC_SET_DEF_PROGRAM             119
#define IDC_LOAD_PROGRAM                120
#define IDC_UNLOAD_PROGRAM              121
#define IDC_GET_FILE                    122
#define IDC_EDIT_FILE                   123
#define IDC_ERASE_FILE                  124
#define IDC_USE_IO                      125
#define IDC_ENTER_PORTAL                126
#define IDC_CRASH                       127
#define IDR_MAINFRAME                   128
#define IDC_GET_MAP                     128
#define IDB_TITLE                       129
#define IDC_BACKDOOR                    129
#define IDC_KILL_ALARM                  130
#define IDC_ATTACK                      131
#define IDC_DECEIVE                     132
#define IDC_ANALYZE                     133
#define IDC_KILL_TRACE                  134
#define IDC_WAIT1                       135
#define IDC_MATRIX_CHAR                 136
#define IDC_MATRIX_DECK                 137
#define IDC_MATRIX_CONTRACT             138
#define IDC_VIEW_ICE                    139
#define IDC_HEALTHBAR_DECK              140
#define IDC_HEALTHBAR_MENTAL            141
#define IDC_HEALTHBAR_LETHAL            142
#define IDC_HEALTHBAR_SHIELD            143
#define IDC_HEALTHBAR_TRANSFER          144
#define IDB_NODE_IL_32                  145
#define IDC_HEALTHBAR_TRACE             145
#define IDB_NODE_IL_16                  146
#define IDC_HEALTHBAR_ICE               146
#define IDC_KILL_SHUTDOWN               147
#define IDC_MAP_VIEW                    148
#define IDC_MESSAGE_VIEW                149
#define IDC_NODE_VIEW                   150
#define IDC_ACTIVE_CHAR                 151
#define IDC_ACTIVE_ICE                  152
#define IDC_ACTIVE_NODE                 153
#define IDC_TARGET_NAME                 154
#define IDC_NODE_NAME                   155
#define IDC_TARGET_PIC                  156
#define IDC_ALARM_BAR                   157
#define IDC_CLOCK                       158
#define IDC_NEXT_TARGET                 159
#define IDC_SCAN                        160
#define IDC_QUICK_LOAD_KEY              161
#define IDC_QUICK_SAVE_KEY              162
#define IDD_NEW_CHAR                    166
#define IDD_OPTIONS                     167
#define IDD_CHAR_DATA                   168
#define IDD_DECK_DATA                   169
#define IDD_CONTRACT_LIST               170
#define IDD_CONTRACT_DATA               171
#define IDD_SHOP                        172
#define IDB_NODE_CPU                    173
#define IDB_NODE_SPU                    174
#define IDB_NODE_DS                     175
#define IDB_NODE_LINE_EW                176
#define IDB_NODE_LINE_NS                177
#define IDB_NODE_IO                     178
#define IDB_NODE_PORTAL                 179
#define IDB_NODE_JUNCTION               180
#define IDB_NODE_COP                    200
#define IDB_IL_ICE                      209
#define IDB_ITEM_IL                     211
#define IDB_SOFTWARE_IL                 212
#define IDB_IL_MISC                     276
#define IDD_TRANSFER                    277
#define IDD_ICE_DATA                    278
#define IDB_IL_TIME                     280
#define IDD_MISSION_RESULTS             281
#define IDD_REST                        282
#define IDD_NEW_PROJECT_DLG             283
#define IDD_PROJECT                     285
#define IDD_ENTRY                       286
#define IDB_UP                          287
#define IDB_DOWN                        288
#define IDD_ORDER_DLG                   288
#define IDR_MESSAGEVIEW_POPUP           292
#define IDR_MATRIX_ACC                  293
#define IDD_BUILD                       294
#define IDB_IL_SPECIAL_NODES_16         296
#define IDB_IL_SPECIAL_NODES_32         297
#define IDD_NAME                        297
#define IDD_SOUND_EDIT                  306
#define IDC_INTRO_NEW                   1000
#define IDC_INTRO_LOAD                  1001
#define IDC_NEW_CHAR_NAME               1003
#define IDC_OPTIONS_LOAD                1004
#define IDC_OPTIONS_SAVE                1005
#define IDC_CHAR_NAME                   1005
#define IDC_OPTIONS_QUIT                1006
#define IDC_CHAR_REPUTATION             1006
#define IDC_CHAR_CREDITS                1007
#define IDC_OPTIONS_SAVEAS              1007
#define IDC_CHAR_LIFESTYLE              1008
#define IDC_OPTIONS_NEW                 1008
#define IDC_CHAR_ATTACK                 1009
#define IDC_OPTIONS_QUICK_LOAD          1009
#define IDC_CHAR_DEFENSE                1010
#define IDC_CHAR_STEALTH                1011
#define IDC_CHAR_ANALYSIS               1012
#define IDC_CHAR_PROGRAMMING            1013
#define IDC_CHAR_CHIP_DESIGN            1014
#define IDC_CHAR_PHYS_HEALTH            1016
#define IDC_CHAR_VIEW_DECK              1017
#define IDC_DECK_CPU                    1018
#define IDC_CHAR_LIFESTYLE_COST         1018
#define IDC_DECK_ATTACK                 1019
#define IDC_CHAR_RENT_DUE_TIME          1019
#define IDC_DECK_DEFENSE                1020
#define IDC_CHAR_LIFESTYLE_UPGRADE_COST 1020
#define IDC_DECK_STEALTH                1021
#define IDC_DECK_ANALYSIS               1022
#define IDC_DECK_OTHER_HW               1023
#define IDC_DECK_VIEW_CHAR              1024
#define IDC_DECK_SOFTWARE               1025
#define IDC_DECK_LOAD                   1026
#define IDC_DECK_CLEAR                  1028
#define IDC_DECK_CURRENT_LOAD           1029
#define IDC_CHAR_SKILL_POINTS           1029
#define IDC_CHAR_INCR_ATTACK            1030
#define IDC_DECK_COP                    1030
#define IDC_CHAR_INCR_DEFENSE           1031
#define IDC_VC_VIEW                     1031
#define IDC_DECK_DEFAULT                1031
#define IDC_CHAR_INCR_STEALTH           1032
#define IDC_VC_CONTRACT_LIST            1032
#define IDC_DECK_TRASH                  1032
#define IDC_CHAR_INCR_ANALYSIS          1033
#define IDC_CONT_DESC                   1033
#define IDC_DECK_RENAME                 1033
#define IDC_CHAR_INCR_PROG              1034
#define IDC_CONT_TYPE                   1034
#define IDC_DECK_SOUND                  1034
#define IDC_CHAR_INCR_CHIP_DES          1035
#define IDC_CONT_TARGET_CORP            1035
#define IDC_CONT_DIFFICULTY             1036
#define IDC_CONT_PAY                    1037
#define IDC_CHAR_LIFESTYLE_UPGRADE      1037
#define IDC_SHOP_ITEM_LIST              1038
#define IDC_CONT_DEADLINE               1038
#define IDC_SHOP_PURCHASE               1039
#define IDC_SHOP_ORDER                  1040
#define IDC_CONT_STATUS2                1040
#define IDC_SHOP_CREDITS                1041
#define IDC_TRANSFER_ITEM_LIST          1042
#define IDC_ICE_NAME                    1043
#define IDC_ICE_TYPE                    1044
#define IDC_ICE_RATING                  1045
#define IDC_ICE_STATUS                  1046
#define IDC_ICE_NOTES                   1047
#define IDC_ICE_PIC                     1051
#define IDC_MR_CONTRACT                 1052
#define IDC_MR_RESULT                   1053
#define IDC_MR_SUMMARY                  1054
#define IDC_MR_PAY                      1055
#define IDC_MR_FILES                    1056
#define IDC_MR_TOTAL                    1057
#define IDC_MR_REP                      1058
#define IDC_MR_SKILL_PTS                1059
#define IDC_HEAL                        1060
#define IDC_HEAL_ALL                    1061
#define IDC_REST_TIME_HOME              1062
#define IDC_REST_TIME_HOME_ALL          1063
#define IDC_REST_TIME_HOSP              1064
#define IDC_REST_TIME_HOSP_ALL          1065
#define IDC_REST_COST_HOSP              1066
#define IDC_REST_COST_HOSP_ALL          1067
#define IDC_HOSP_HEAL                   1068
#define IDC_HOSP_HEAL_ALL               1069
#define IDC_REST_DATE                   1070
#define IDC_REST_HEALTH                 1071
#define IDC_REST_MONEY                  1072
#define IDC_REST_WAIT                   1073
#define IDC_PROJ_TYPE                   1074
#define IDC_PROJ_CLASS                  1075
#define IDC_PROJ_CHIP_TYPE              1075
#define IDC_PROJ_SOURCE                 1076
#define IDC_PROJ_RATING                 1077
#define IDC_PROJ_CHIP_TIME              1077
#define IDC_PROJ_TIME                   1078
#define IDC_PROJ_SKILL                  1079
#define IDC_PROJ_WORK_DAY               1079
#define IDC_PROJ_NEW                    1080
#define IDC_PROJ_FINISH                 1081
#define IDC_PROJ_BUILD                  1082
#define IDC_PROJ_WORK_WEEK              1083
#define IDC_PROJ_DATE                   1084
#define IDC_TEXT                        1085
#define IDC_PROJ_TRASH                  1085
#define IDC_DECK_UP                     1087
#define IDC_DECK_DOWN                   1088
#define IDC_ORDER_TYPE                  1088
#define IDC_ORDER_CLASS                 1089
#define IDC_ORDER_RATING                1090
#define IDC_ORDER_COST                  1091
#define IDC_ORDER_TIME                  1092
#define IDC_DECK_LOAD_LIGHT             1093
#define IDC_DECK_LOAD_AVERAGE           1094
#define IDC_TRANSFER_LOAD               1094
#define IDC_DECK_LOAD_HEAVY             1095
#define IDC_TRANSFER_LOAD_TEXT          1095
#define IDC_TRANSFER_AFTER_TEXT         1096
#define IDC_TRANSFER_AFTER              1097
#define IDC_TRANSFER_LIGHT_TEXT         1098
#define IDC_TRANSFER_AVERAGE_TEXT       1099
#define IDC_TRANSFER_HEAVY_TEXT         1100
#define IDC_TRANSFER_LIGHT              1101
#define IDC_TRANSFER_AVERAGE            1102
#define IDC_TRANSFER_HEAVY              1103
#define IDC_NEW_CHAR_IMAGE              1104
#define IDC_NEW_CHAR_IMAGE_SPIN         1105
#define IDC_VERSION                     1106
#define IDC_CHAR_DATE                   1107
#define IDC_BUILD_LOAD                  1108
#define IDC_CHAR_IRONMAN                1108
#define IDC_BUILD_TEXT                  1109
#define IDC_BUILD_UNLOAD                1110
#define IDC_NEW_CHAR_BONUS1             1110
#define IDC_BUILD_TRASH                 1111
#define IDC_NEW_CHAR_BONUS2             1111
#define IDC_NAME_TEXT                   1111
#define IDC_NEW_CHAR_BONUS3             1112
#define IDC_NEW_CHAR_BONUS              1113
#define IDC_NEW_CHAR_BONUS4             1114
#define IDC_NEW_CHAR_IRONMAN            1115
#define IDC_OPTIONS_TOOLTIPS            1116
#define IDC_NEW_CHAR_TOOLTIPS           1116
#define IDC_SOUND_LIST                  1118
#define IDC_SOUND_PLAY                  1119
#define IDC_OPTIONS_SOUND               1121
#define IDC_CONT_STATUS1                1122
#define ID_MSGVIEWMENU_CLEAR            32771
#define IDC_EVALUATE                    32772
#define IDC_SMOKE                       32773
#define IDC_SILENCE                     32774
#define IDC_MEDIC                       32775
#define IDC_RELOCATE                    32776
#define IDC_DECRYPT                     32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        307
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1123
#define _APS_NEXT_SYMED_VALUE           163
#endif
#endif
